site_name: Dinesh Mistry Tutorials
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/dmancloud
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/dineshmistry
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@dineshmistry

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 Dinesh Mistry</a>
  