name: ci
on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write      

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.2
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material mkdocs-git-revision-date-localized-plugin mike
      - run: |
          git config --global user.name dmancloud
          git config --global user.email dinesh@dman.cloud
      - run: mike deploy --push 0.0.1
      - run: mike deploy --update-aliases 0.0.1 latest
      - run: mike set-default latest
      #- run: mkdocs gh-deploy --force
